AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: hello-world
      Runtime: go1.x
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-west-2:012345678901:my-queue
            BatchSize: 10
            Enabled: true
      Environment:
        Variables:
          PARAM1: VALUE
